[
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 1,
    counter_value: 0,
    is_collision: 1,
    dist_squared: 1.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 2,
    counter_value: 0,
    is_collision: 1,
    dist_squared: 1.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 1,
    entity2: 2,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 2.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
  {
    entity1: 0,
    entity2: 3,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 2.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 1,
    entity2: 3,
    counter_value: 0,
    is_collision: 1,
    dist_squared: 1.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 2,
    entity2: 3,
    counter_value: 0,
    is_collision: 1,
    dist_squared: 1.0,
    rad_sum_sq: 1.44,
    rad_mult: 1.0,
  },
  {
    entity1: 0,
    entity2: 0,
    counter_value: 0,
    is_collision: 0,
    dist_squared: 0.0,
    rad_sum_sq: 0.0,
    rad_mult: 0.0,
  },
];
