mod allowed_types;
mod compilation_metadata;
mod compilation_unit;
mod compile_error;
mod custom_types;
pub mod lib;
mod module_parser;
mod output;
mod phases;
mod remove_doc_comments;
mod state;
mod to_wgsl_syntax;
mod transform_wgsl_helper_methods;
